version: 2.1
orbs:
  ruby: circleci/ruby@2.0.0

jobs:
  test:
    parameters:
      ruby-version:
        type: string
      rails-version:
        type: string
    docker:
      - image: cimg/ruby:<< parameters.ruby-version >>
    environment:
      - RAILS_VERSION: << parameters.rails-version >>
    steps:
      - checkout
      - ruby/install-deps:
          key: gems-v2-<< parameters.ruby-version >>-<< parameters.rails-version >>-
      - ruby/rspec-test

  rubocop:
    docker:
      - image: 'cimg/ruby:2.7'
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rubocop-check:
          format: progress
          label: Inspecting with Rubocop

workflows:
  tests:
    jobs:
      - test:
          matrix:
            parameters:
              rails-version: ["6.1", "7.0"]
              ruby-version: ["2.7.7", "3.0.5", "3.1.3"]

  code_quality:
    jobs:
      - rubocop:
          filters:
            branches:
              ignore:
                - master
                - main
