version: 2.1
orbs:
  ruby: circleci/ruby@1.1.4

jobs:
  test-ruby-2:
    docker:
      - image: cimg/ruby:2.7
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/install-deps
      - ruby/rspec-test

  test-ruby-3:
    docker:
      - image: cimg/ruby:3.0
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/install-deps
      - ruby/rspec-test

  rubocop:
    docker:
      - image: 'cimg/ruby:2.7'
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rubocop-check:
          format: progress
          label: Inspecting with Rubocop

workflows:
  tests:
    jobs:
      - test-ruby-2
      - test-ruby-3
  code_quality:
    jobs:
      - rubocop:
          filters:
            branches:
              ignore:
                - master
                - main
