version: 2.1
orbs:
  ruby: circleci/ruby@1.1.4

jobs:
  test:
    docker:
      - image: cimg/ruby:3.1
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rspec-test

  rubocop:
    docker:
      - image: 'cimg/ruby:3.1'
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rubocop-check:
          format: progress
          label: Inspecting with Rubocop

workflows:
  tests:
    jobs:
      - test
  code_quality:
    jobs:
      - rubocop:
          filters:
            branches:
              ignore:
                - master
                - main
