name: 'Code quality'
on:
  workflow_call:

jobs:
  code_quality:
    runs-on: ubuntu-latest
    needs:
      - rubocop
    steps:
      - run: echo "All code quality checks complete."

  rubocop:
    runs-on: ubuntu-latest
    steps:
      - name: Inspecting with Rubocop
        run: rubocop
